<?php

use Illuminate\Database\Seeder;
use App\Models\CentroReclusion;

class CatCentroReclusionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_centro_reclusion')->insert([
            ['entidad' => 'AGUASCALIENTES', 'nombre' => 'CERESO VARONIL AGUASCALIENTES'],
            ['entidad' => 'AGUASCALIENTES', 'nombre' => 'CERESO EL LLANO'],
            ['entidad' => 'AGUASCALIENTES', 'nombre' => 'CERESO FEMENIL AGUASCALIENTES'],
            ['entidad' => 'BAJA CALIFORNIA', 'nombre' => 'CE.RE.SO. HONGO I'],
            ['entidad' => 'BAJA CALIFORNIA', 'nombre' => 'CE.RE.SO. HONGO II'],
            ['entidad' => 'BAJA CALIFORNIA', 'nombre' => 'CERESO ENSENADA'],
            ['entidad' => 'BAJA CALIFORNIA', 'nombre' => 'CERESO MEXICALI'],
            ['entidad' => 'BAJA CALIFORNIA', 'nombre' => 'CARCEL PUBLICA TIJUANA (LA OCHO)'],
            ['entidad' => 'BAJA CALIFORNIA SUR', 'nombre' => 'CERESO CIUDAD CONSTITUCION'],
            ['entidad' => 'BAJA CALIFORNIA SUR', 'nombre' => 'CENTRO DE REINSERCION SOCIAL DE SAN JOSE DEL CABO'],
            ['entidad' => 'BAJA CALIFORNIA SUR', 'nombre' => 'CERESO LA PAZ'],
            ['entidad' => 'BAJA CALIFORNIA SUR', 'nombre' => 'CENTRO REGIONAL DE READAPTACION SOCIAL DE LORETO'],
            ['entidad' => 'BAJA CALIFORNIA SUR', 'nombre' => 'CERESO SANTA ROSALIA'],
            ['entidad' => 'CAMPECHE', 'nombre' => 'CERESO CIUDAD DEL CARMEN'],
            ['entidad' => 'CAMPECHE', 'nombre' => 'CERESO SAN FRANCISCO KOBEN'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO CIUDAD ACUÑA'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO PIEDRAS NEGRAS'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO SABINAS'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO FEMENIL SALTILLO'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO SALTILLO'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO SAN PEDRO'],
            ['entidad' => 'COAHUILA', 'nombre' => 'CERESO TORREON'],
            ['entidad' => 'COLIMA', 'nombre' => 'CERESO COLIMA'],
            ['entidad' => 'COLIMA', 'nombre' => 'CARCEL MUNICIPAL MANZANILLO'],
            ['entidad' => 'COLIMA', 'nombre' => 'RECLUSORIO PREVENTIVO DE TECOMAN'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CEP 01, CHIAPA DE CORZO'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 3 TAPACHULA VARONIL'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 4 FEMENIL TAPACHULA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 5 SAN CRISTOBAL DE LAS CASAS'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERSS 06, MOTOZINTLA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 7 HUIXTLA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 8 VILLA FLORES'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 9 ACAPETAHUA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 10 COMITAN DE DOMINGUEZ'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 11 PICHUCALCO'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERESO NUM. 12 YAJALON'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERSS 13, TONALA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERSS 14, CINTALAPA'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERSS 16, OCOSINGO'],
            ['entidad' => 'CHIAPAS', 'nombre' => 'CERSS 17, CATAZAJA'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CERESO DISTRITAL CAMARGO'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CERESO DISTRITAL GUACHOCHI'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CERSO ESTATAL NO 1'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CE.RE.SO. ESTATAL NO. 4'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CERESO ESTATAL No 5'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CERESO ESTATAL No.3'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CE.RE.SO. ESTATAL NO. 6'],
            ['entidad' => 'CHIHUAHUA', 'nombre' => 'CE.RE.SO. ESTATAL NO. 4'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO DE EJECUCION DE SANCIONES PENALES VARONIL NORTE'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO DE EJECUCION DE SANCIONES PENALES VARONIL ORIENTE'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO DE READAPTACION SOCIAL VARONIL SANTA MARTHA ACATITLA'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO FEMENIL DE READAPTACION SOCIAL SANTA MARTHA ACATITLA'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO FEMENIL DE READAPTACION SOCIAL'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'CENTRO VARONIL DE REHABILITACIÓN PSICOSOCIAL'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'PENITENCIARIA STA. MARTHA ACATITLA'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'RECLUSORIO PREVENTIVO NORTE'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'RECLUSORIO PREVENTIVO ORIENTE'],
            ['entidad' => 'DISTRITO FEDERAL', 'nombre' => 'RECLUSORIO PREVENTIVO SUR'],
            ['entidad' => 'DURANGO', 'nombre' => 'CERESO NO. 2 GOMEZ PALACIO'],
            ['entidad' => 'DURANGO', 'nombre' => 'CERESO NO. 1 DURANGO'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO ACAMBARO'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CELAYA'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO GUANAJUATO'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO IRAPUATO'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO LEON'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO PENJAMO'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CARCEL MUNICIPAL SALAMANCA'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO SAN FELIPE'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO SAN MIGUEL DE ALLENDE'],
            ['entidad' => 'GUANAJUATO', 'nombre' => 'CERESO VALLE DE SANTIAGO ( 1000 )'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO ACAPULCO DE JUAREZ'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO ARCELIA'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO AYUTLA DE LOS LIBRES'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO CHILAPA DE ALVAREZ'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO CHILPANCINGO DE LOS BRAVO'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO COYUCA DE CATALAN'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO IGUALA DE LA INDEPENDENCIA'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CENTRO REGIONAL DE READAP. SOCIAL LA UNION'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO MALINALTEPEC'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO OMETEPEC'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO SAN LUIS ACATLAN'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO TAXCO DE ALARCON'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO TECPAN'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO TELOLOAPAN'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO TIXTLA DE GUERRERO'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO TLAPA DE COMONFORT'],
            ['entidad' => 'GUERRERO', 'nombre' => 'CERESO ZIHUATANEJO'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CARCEL DISTRITAL ZACUALTIPAN'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO ACTOPAN'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO APAN'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO HUICHAPAN'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO IXMIQUILPAN'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO JACALA'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO HUASTECA HIDALGUENSE'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO MIXQUIAHUALA'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO MOLANGO'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO PACHUCA'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO TENANGO DE DORIA'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO TULA'],
            ['entidad' => 'HIDALGO', 'nombre' => 'CERESO TULANCINGO'],
            ['entidad' => 'JALISCO', 'nombre' => 'CARCEL MUNICIPAL CHAPALA'],
            ['entidad' => 'JALISCO', 'nombre' => 'CARCEL MUNICIPAL AUTLAN'],
            ['entidad' => 'JALISCO', 'nombre' => 'CEINJURE DE CIUDAD GUZMAN'],
            ['entidad' => 'JALISCO', 'nombre' => 'CARCEL MUNICIPAL LAGOS DE MORENO'],
            ['entidad' => 'JALISCO', 'nombre' => 'CEINJURE PUERTO VALLARTA'],
            ['entidad' => 'JALISCO', 'nombre' => 'CEINJURE TEPATITLAN DE MORELOS'],
            ['entidad' => 'JALISCO', 'nombre' => 'CARCEL MUNICIPAL TEQUILA'],
            ['entidad' => 'JALISCO', 'nombre' => 'CEINJURE VALLES DE AMECA'],
            ['entidad' => 'JALISCO', 'nombre' => 'CENTRO PREVENTIVO DE RECLUSION FEMENIL DE GUADALAJARA'],
            ['entidad' => 'JALISCO', 'nombre' => 'CERESO NO. 1 PUENTE GRANDE'],
            ['entidad' => 'JALISCO', 'nombre' => 'RECLUSORIO PREVENTIVO DE GUADALAJARA'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. CHALCO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. CUAUTITLAN'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. ECATEPEC'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. EL ORO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. IXTLAHUACA'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. JILOTEPEC'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. LERMA'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. NEZAHUALCOYOTL BORDO XOCHIACA'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. OTUMBA'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. SULTEPEC'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. TEMASCALTEPEC'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. TENANCINGO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. VALLE DE BRAVO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. TEXCOCO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. TLALNEPANTLA DE BAZ'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. VALLE DE BRAVO'],
            ['entidad' => 'MEXICO', 'nombre' => 'C. P. R. S. ZUMPANGO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO LIC. DAVID FRANCO RODRIGUEZ'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO GRAL. FRANCISCO J. MUGICA'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO LIC. EDUARDO RUIZ - URUAPAN'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV APATZINGÁN'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV ARIO DE ROSALES'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV CD. HIDALGO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV COALCOMÁN'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV HUETAMO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV JIQUILPAN'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO LA PIEDAD'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO LÁZARO CARDENAS LA MIRA'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV LOS REYES'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO MARAVATIO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV PATZCUARO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV PURUANDIRO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'RECLUSORIO PREVENTIVO SAHUAYO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO TACÁMBARO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV TANHUATO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV ZACAPU'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO ZAMORA'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CEPREV ZINAPECUARO'],
            ['entidad' => 'MICHOACAN', 'nombre' => 'CERESO HNOS. LÓPEZ RAYÓN ZITÁCUARO'],
            ['entidad' => 'MORELOS', 'nombre' => 'CARCEL DISTRITAL CUAUTLA'],
            ['entidad' => 'MORELOS', 'nombre' => 'CARCEL DISTRITAL JOJUTLA'],
            ['entidad' => 'MORELOS', 'nombre' => 'CARCEL DISTRITAL JONACATEPEC'],
            ['entidad' => 'MORELOS', 'nombre' => 'CARCEL PUENTE DE IXTLA'],
            ['entidad' => 'MORELOS', 'nombre' => 'CARCEL DISTRITAL TETECALA'],
            ['entidad' => 'MORELOS', 'nombre' => 'CERESO MORELOS FEMENIL'],
            ['entidad' => 'MORELOS', 'nombre' => 'CERESO MORELOS VARONIL'],
            ['entidad' => 'NAYARIT', 'nombre' => 'CERESO NAYARIT VENUSTIANO CARRANZA'],
            ['entidad' => 'NUEVO LEON', 'nombre' => 'CERESO APODACA NUEVO LEON'],
            ['entidad' => 'NUEVO LEON', 'nombre' => 'CERESO MONTERREY TOPO CHICO'],
            ['entidad' => 'NUEVO LEON', 'nombre' => 'CERESO CADEREYTA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL SANTO DOMINGO TEHUANTEPEC'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL COSOLAPA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL SAN JUAN BAUTISTA CUICATLAN'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL VILLA DE ETLA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL HUAJUAPAN DE LEON'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL JUCHITAN DE ZARAGOZA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL SANTA CATARINA JUQUILA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL MATIAS ROMERO AVENDAÑO'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL MIAHUATLAN DE PORFIRIO DIAZ'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL SAN PEDRO POCHUTLA'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO DISTRITAL TLACOLULA DE MATAMOROS'],
            ['entidad' => 'OAXACA', 'nombre' => 'CENTRO DE INTERNAMIENTO DE TLAXIACO'],
            ['entidad' => 'OAXACA', 'nombre' => 'RECLUSORIO REGIONAL SAN JUAN BAUTISTA TUXTEPEC'],
            ['entidad' => 'OAXACA', 'nombre' => 'PENITENCIARIA CENTRAL OAXACA DE JUAREZ SANTA MARIA IXCOTEL'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL ACATLAN DE OSORIO'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL ATLIXCO'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL CHIAUTLA DE TAPIA'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL CHIGNAHUAPAN'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL LIBRES'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TECALI DE HERRERA'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TECAMACHALCO'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TEPEACA'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TETELA DE OCAMPO'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TEZIUTLAN'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL TLATLAUQUITEPEC'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL XICOTEPEC DE JUAREZ'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL ZACAPOAXTLA'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL DISTRITAL ZACATLAN'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL MUNICIPAL CIUDAD SERDAN'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CARCEL MUNICIPAL TEPEXI DE RODRIGUEZ'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CERESO PUEBLA'],
            ['entidad' => 'PUEBLA', 'nombre' => 'CERESO TEHUACAN'],
            ['entidad' => 'QUERETARO', 'nombre' => 'CERESO JALPAN DE SERRA'],
            ['entidad' => 'QUERETARO', 'nombre' => 'CERESO QUERETARO SAN JOSE EL ALTO'],
            ['entidad' => 'QUERETARO', 'nombre' => 'CERESO SAN JUAN DEL RIO'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CARCEL MUNICIPAL CANCUN'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CARCEL MUNICIPAL DE COZUMEL'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CARCEL MUNICIPAL DE FELIPE CARRILLO PUERTO'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CARCEL MUNICIPAL DE ISLA MUJERES'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CARCEL MUNICIPAL DE PLAYA DEL CARMEN'],
            ['entidad' => 'QUINTANA ROO', 'nombre' => 'CERESO CHETUMAL'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. MATEHUALA'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION ESTATAL DE RIO VERDE'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION ESTATAL TAMAZUNCHALE'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION ESTATAL DE TANCAHUITZ (EL XOLOL)'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. CARDENAS'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. CERRITOS'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. CIUDAD DEL MAIZ'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO ESTATAL DE RECLUSION DE CIUDAD VALLES'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. DE VENADO'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. GUADALCAZAR'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. SALINAS DE HIDALGO'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CENTRO DE RECLUSION DTTAL. SANTA MARIA DEL RIO'],
            ['entidad' => 'SAN LUIS POTOSI', 'nombre' => 'CE.PRE.RE.SO. NO. 1 DELEGACION LA PILA'],
            ['entidad' => 'SINALOA', 'nombre' => 'CENTRO DE EJEC. DE LAS CONSEC. JUR. DEL. DELITO CULIACAN'],
            ['entidad' => 'SINALOA', 'nombre' => 'CENTRO DE EJEC. DE LAS CONSEC. JUR. DEL. DELITO MAZATLAN'],
            ['entidad' => 'SINALOA', 'nombre' => 'CENTRO DE EJEC. DE LAS CONSEC. JUR. DEL. DELITO LOS MOCHIS'],
            ['entidad' => 'SONORA', 'nombre' => 'CENTRO DE READAPTACION SOCIAL HERMOSILLO II'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO GUAYMAS'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO CABORCA'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO CANANEA'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO CIUDAD OBREGON'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO NAVOJOA'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO AGUA PRIETA'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO MAGDALENA'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO PUERTO PEÑASCO'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO HERMOSILLO'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO HUATABAMPO'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO NOGALES I'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO NOGALES FEMENIL'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO NOGALES II VARONIL'],
            ['entidad' => 'SONORA', 'nombre' => 'CERESO SAN LUIS RIO COLORADO'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO DE CARDENAS LAS PALMAS'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO DE COMALCALCO'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO VILLAHERMOSA CRESET'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO HUIMANGUILLO'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO MACUSPANA'],
            ['entidad' => 'TABASCO', 'nombre' => 'CERESO TENOSIQUE'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'CENTRO REGIONAL ALTAMIRA'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'RECLUSORIO PREVENTIVO CIUDAD MANTE'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'CERESO MATAMOROS 2'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'RECLUSORIO PREVENTIVO MIGUEL ALEMAN'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'CERESO NUEVO LAREDO 2'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'CERESO REYNOSA'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'RECLUSORIO PREVENTIVO TULA'],
            ['entidad' => 'TAMAULIPAS', 'nombre' => 'CERESO CIUDAD VICTORIA'],
            ['entidad' => 'TLAXCALA', 'nombre' => 'CERESO TLAXCALA'],
            ['entidad' => 'TLAXCALA', 'nombre' => 'CERESO APIZACO'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO AMATLAN DE LOS REYES'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO COATZACOALCOS'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO PACHO VIEJO'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO TUXPAN'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO ACAYUCAN'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO CHICONTEPEC'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO COSAMALOAPAN'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO HUAYACOCOTLA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO JALACINGO'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO MISANTLA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO OZULUAMA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO PANUCO'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO PAPANTLA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO POZA RICA DE HIDALGO'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO SAN ANDRES TUXTLA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO TANTOYUCA'],
            ['entidad' => 'VERACRUZ', 'nombre' => 'CERESO ZONGOLICA'],
            ['entidad' => 'YUCATAN', 'nombre' => 'CENTRO DE PREVENCION Y REINSERCION SOCIAL MERIDA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CERERESO FRESNILLO'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CERERESO ZACATECAS VARONIL CIENEGUILLAS'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CERESO FEMENIL ZACATECAS'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL JALPA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL LORETO'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL VILLANUEVA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO NOCHISTLAN DE MEJIA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL TLALTENANGO'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL JEREZ DE GARCIA SALI'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CARCEL DISTRITAL DE MIGUEL AUZA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL. OJO CALIENTE'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL. PINOS'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CERESO SOMBRERETE'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL. TEUL DE GLEZ. ORTEGA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'CARCEL DISTRITAL VALPARAISO'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL. RIO GRANDE'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL CONCEPCION DEL ORO'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DISTRITAL JUCHIPILA'],
            ['entidad' => 'ZACATECAS', 'nombre' => 'ESTABLECIMIENTO PENITENCIARIO DTTAL. CALERA'],
        ]);        
    }
}
