<?php

use Illuminate\Database\Seeder;

class CatSubParticularidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         DB::table('cat_sub_particularidades')->insert([
         	['idParticularidadesCuerpo'=>1, 'nombre' => 'LACIO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'SEMIONDULADO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ONDULADO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'RIZADO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'CRESPO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'CALVO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ALOPECIA FRONTAL'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ALOPECIA CORONAL'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ALOPECIA TONSURAL'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ALOPECIA BILATERAL'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'ALOPECIA INCIPIENTE'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'CORTO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'MEDIANO AL HOMBRO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'LARGO'],
            ['idParticularidadesCuerpo'=>1, 'nombre' => 'RAPADO'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'ACNÉ'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'CXT ACNÉ'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'MANCHAS'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'PECAS'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'VERRUGAS'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'LUNARES'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'POBLADA'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'REGULAR'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'ESCASA'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'DEPILADA'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'RASURADA'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'SIN CEJA'],
         	['idParticularidadesCuerpo'=>4, 'nombre' => 'COLOR DIFERENTE'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'CATARATA'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'CIEGO'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'BIZCO'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'OJO DE VIDRIO'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'LENTES DE CONTACTO'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'ANTEOJOS/GAFAS'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'FALTA OJO'],
            ['idParticularidadesCuerpo'=>5, 'nombre' => 'COMPLETA'],
            ['idParticularidadesCuerpo'=>5, 'nombre' => 'INCOMPLETA'],
            ['idParticularidadesCuerpo'=>5, 'nombre' => 'OBLITERADA'],
            ['idParticularidadesCuerpo'=>6, 'nombre' => 'POBLADA'],
            ['idParticularidadesCuerpo'=>6, 'nombre' => 'ESCASA'],
            ['idParticularidadesCuerpo'=>6, 'nombre' => 'LAMPIÑO'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'ACNÉ'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'CXT ACNÉ'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'MANCHAS'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'PECAS'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'VERRUGAS'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'LUNARES'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'CHATA/BOTÓN'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'AGUILEÑA'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'RESPINGADA/RECTA'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'OBLITERADA'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'ACNÉ'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'CXT ACNÉ'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'MANCHAS'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'PECAS'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'VERRUGAS'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'LUNARES'],
            ['idParticularidadesCuerpo'=>9, 'nombre' => 'POBLADA'],
            ['idParticularidadesCuerpo'=>9, 'nombre' => 'ESCASA'],
            ['idParticularidadesCuerpo'=>9, 'nombre' => 'LAMPIÑO'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'DELGADO'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'MEDIANO'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'GRUESO'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'MIXTO'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'ACNÉ'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'CXT ACNÉ'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'MANCHAS'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'PECAS'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'VERRUGAS'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'LUNARES'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'SALIENTE'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'RECTO'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'RETRAÍDO'],        
            ['idParticularidadesCuerpo'=>12, 'nombre' => 'POBLADA'],
            ['idParticularidadesCuerpo'=>12, 'nombre' => 'ESCASA'],
            ['idParticularidadesCuerpo'=>12, 'nombre' => 'LAMPIÑO'],

            ['idParticularidadesCuerpo'=>1, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>5, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>6, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>9, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'OTRO'],
            ['idParticularidadesCuerpo'=>12, 'nombre' => 'OTRO'],

            ['idParticularidadesCuerpo'=>1, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>2, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>3, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>4, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>5, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>6, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>7, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>8, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>9, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>10, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>11, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>12, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>13, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>14, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>15, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>16, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>17, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>18, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>19, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>20, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>21, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>22, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>23, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>24, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>25, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>26, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>27, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>28, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>29, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>30, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>31, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>32, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>33, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>34, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>35, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>36, 'nombre' => 'SIN INFORMACIÓN'],
            ['idParticularidadesCuerpo'=>37, 'nombre' => 'SIN INFORMACIÓN'],
        ]);
    }
}
