<?php
use Illuminate\Database\Seeder;
class ColoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_colores')->insert([
            [ 'nombre' => 'AZUL', 'codigo' => '#0099CC' ],
            [ 'nombre' => 'AZUL CLARO', 'codigo' => '#91e4ed' ],
            [ 'nombre' => 'AZUL ELÉCTRICO', 'codigo' => '#1974ba' ],
            [ 'nombre' => 'AZUL MARINO', 'codigo' => '#19157e' ],
            [ 'nombre' => 'AZUL MEDIO', 'codigo' => '#1b62ba' ],
            [ 'nombre' => 'AZUL OBSCURO', 'codigo' => '#043048' ],
            [ 'nombre' => 'AZUL PLUMBAGO', 'codigo' => '#044363' ],
            [ 'nombre' => 'BLANCO', 'codigo' => '#FFFFFF' ],
            [ 'nombre' => 'CAFÉ', 'codigo' => '#43280c' ],
            [ 'nombre' => 'GRAFITO', 'codigo' => '#38383a' ],
            [ 'nombre' => 'GRIS', 'codigo' => '#c6c7c9' ],
            [ 'nombre' => 'GRIS ACERO', 'codigo' => '#87888a' ],
            [ 'nombre' => 'GRIS CLARO', 'codigo' => '#ededef' ],
            [ 'nombre' => 'GRIS OBSCURO', 'codigo' => '#38383a' ],
            [ 'nombre' => 'HUESO', 'codigo' => '#fef6e8' ],
            [ 'nombre' => 'INDIGO', 'codigo' => '#053e69' ],
            [ 'nombre' => 'KHAKI', 'codigo' => '#d1b18a' ],
            [ 'nombre' => 'NEGRO', 'codigo' => '#000000' ],
            [ 'nombre' => 'NEGRO INTENSO', 'codigo' => '#000000' ],
            [ 'nombre' => 'NEGRO SUAVIZADO', 'codigo' => '#1d1d1d' ],
            [ 'nombre' => 'SIN COLOR', 'codigo' => '#FFFFFF' ],
            [ 'nombre' => 'AGUA', 'codigo' => '#5fdbe0' ],
            [ 'nombre' => 'ALMENDRA', 'codigo' => '#d1b18a' ],
            [ 'nombre' => 'AMARILLO', 'codigo' => '#FFCC33' ],
            [ 'nombre' => 'AMARILLO CLARO', 'codigo' => '#feef8b' ],
            [ 'nombre' => 'ARENA', 'codigo' => '#f7dfb4' ],            
            [ 'nombre' => 'AZUL BRILLANTE', 'codigo' => '#199fdd' ],
            [ 'nombre' => 'AZUL CELESTE', 'codigo' => '#bef0f5' ],           
            [ 'nombre' => 'AZUL MEDIO', 'codigo' => '#1b62ba' ],
            [ 'nombre' => 'AZUL OBSCURO', 'codigo' => '#043048' ],
            [ 'nombre' => 'AZUL PAVO', 'codigo' => '#1b1d8b' ],
            [ 'nombre' => 'AZUL PIZARRA', 'codigo' => '#0c60b3' ],
            [ 'nombre' => 'AZUL PLUMBAGO', 'codigo' => '#044363' ],
            [ 'nombre' => 'AZUL REY', 'codigo' => '#117db5' ],
            [ 'nombre' => 'BEIGE', 'codigo' => '#fadca1' ],
            [ 'nombre' => 'BERENJENA', 'codigo' => '#400926' ],
            [ 'nombre' => 'BLANCO', 'codigo' => '#FFFFFF' ],
            [ 'nombre' => 'CAFÉ', 'codigo' => '#43280c' ],
            [ 'nombre' => 'CAFÉ CLARO', 'codigo' => '#b59f8e' ],
            [ 'nombre' => 'CAFÉ OBSCURO', 'codigo' => '#3e2c26' ],
            [ 'nombre' => 'CEMENTO', 'codigo' => '#7b7c7e' ],
            [ 'nombre' => 'CEREZA', 'codigo' => '#e22640' ],
            [ 'nombre' => 'COBALTO', 'codigo' => '#0e347d' ],
            [ 'nombre' => 'CORAL', 'codigo' => '#f06f6f' ],
            [ 'nombre' => 'CREMA', 'codigo' => '#fcfced' ],
            [ 'nombre' => 'DURAZNO', 'codigo' => '#f0b890' ],
            [ 'nombre' => 'FRAMBUESA', 'codigo' => '#e1155e' ],
            [ 'nombre' => 'FUCSIA', 'codigo' => '#ff0080' ],
            [ 'nombre' => 'GRAFITO', 'codigo' => '#38383a' ],
            [ 'nombre' => 'GRIS', 'codigo' => '#c6c7c9' ],
            [ 'nombre' => 'GRIS ACERO', 'codigo' => '#87888a' ],
            [ 'nombre' => 'GRIS CLARO', 'codigo' => '#ededef' ],
            [ 'nombre' => 'GRIS MEDIO', 'codigo' => '#b2b3b5' ],
            [ 'nombre' => 'GRIS OBSCURO', 'codigo' => '#38383a' ],
            [ 'nombre' => 'GRIS OXFORD', 'codigo' => '#4b4b4d' ],
            [ 'nombre' => 'HUESO', 'codigo' => '#fef6e8' ],
            [ 'nombre' => 'JADE', 'codigo' => '#107e73' ],
            [ 'nombre' => 'KHAKI', 'codigo' => '#d1b18a' ],
            [ 'nombre' => 'LADRILLO', 'codigo' => '#802e2e' ],
            [ 'nombre' => 'LILA', 'codigo' => '#c19ad0' ],
            [ 'nombre' => 'MAGENTA', 'codigo' => '#d6237a' ],
            [ 'nombre' => 'MARFIL', 'codigo' => '#fdfbed' ],
            [ 'nombre' => 'MELÓN', 'codigo' => '#f26c5d' ],
            [ 'nombre' => 'MENTA', 'codigo' => '#6fc2b2' ],
            [ 'nombre' => 'MORADO', 'codigo' => '#652f71' ],
            [ 'nombre' => 'MORADO CLARO', 'codigo' => '#9d50a8' ],     
        ]);
    }
}
