<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<center><p class="fuente">SOLICITUD DE PERSONAS EXTRAVIADAS, SUSTRAIDAS O AUSENTES</p></center>
	<div id="emisor">
		
		<p ><strong class="fuente">LIC.</strong> <strong class="fuente">DAVID GARCÍA GALVÁN</strong></p>
		<p > FISCAL ESPECIALIZADO EN ATENCIÓN DE DENUNCIAS POR PERSONAS DESAPARECIDAS.</p>
		<p >ZONA CENTRO XALAPA.</p>	
	</div>

	<div id="cuerpo">
		<p>CON FUNDAMENTO EN EL ARTICULO 8° DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS, LA QUE SUSCRIBE LUZ DEL ROSARIO MENDOZA GERÓN, CON DOMICILIO PARA OÍR Y RECIBIR TODO TIPO DE NOTIFICACIONES Y DOCUMENTOS EL UBICADO EN CALLE ÁLVARO OBREGÓN, SIN NÚMERO, COLONIA LOS PINOS, LOCALIDAD RINCONADA, MUNICIPIO DE EMILIANO ZAPATA, VERACRUZ, RESPETUOSAMENTE ME DIRIJO ANTE USTED PARA INFORMAR QUE MI PAREJA DE 25 AÑOS DE EDAD, DE QUIEN SE DESCONOCE SU PARADERO DESDE EL DÍA 11 DE JUNIO DE 2018, SIENDO LAS 15:00 APROXIMADAMENTE, RAZÓN POR LA CUAL ME PERMITO SOLICITAR DE LA MANERA MAS ATENTA, SE ELABORE LA CÉDULA DE IDENTIFICACIÓN CON LA IMAGEN Y MEDIA FILIACIÓN DE DICHA PERSONA Y SE DIFUNDA A NIVEL NACIONAL A TRAVÉS DE LAS FISCALÍAS Y/O PROCURADURÍAS GENERALES DE JUSTICIA DE LOS ESTADOS DE LA REPUBLICA, ASÍ COMO DE LAS SUBPROCURADURÍAS Y DE LAS DELEGACIONES ESTATALES DE LA PROCURADURÍA GENERAL DE LA REPUBLICA Y DE SU PAGINA DE INTERNET. PARA MAYOR CONOCIMIENTO, ANEXO LA SIGUIENTE DOCUMENTACIÓN EN COPIA SIMPLE:</p>

		<p>
			<table>
				<caption>table title and/or explanatory text</caption>
				<thead>
					<tr>
						<th>header</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th>ACTA DE NACIMIENTO DE LA PERSONA EXTRAVIADA</th>
						<td>NO</td>
					</tr>
				</tbody>
			</table>
		</p>
	</div>
	




</body>
</html>